# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-27 08:38
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
import home.blocks
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0030_index_on_pagerevision_created_at'),
        ('home', '0003_address_calenderevent_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('blog_content', wagtail.wagtailcore.fields.StreamField((('blog_title', wagtail.wagtailcore.blocks.StructBlock((), help_text='Dit is de titel van het artikel, voorzien van een afbeelding')), ('blog_intro', home.blocks.IntroTextBlock(help_text='Hiermee kan je optioneel een korte inleiding voorzien')), ('blog_subtitle', home.blocks.SubtitleBlock()), ('blog_paragraph', home.blocks.ParagraphBlock()), ('blog_image', wagtail.wagtailcore.blocks.StructBlock(())), ('blog_quote', wagtail.wagtailcore.blocks.StructBlock(()))), verbose_name='Blog inhoud')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='NewsArticle',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('name', models.CharField(max_length=164, verbose_name='naam')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.AlterField(
            model_name='calenderevent',
            name='description',
            field=models.TextField(verbose_name='beschrijving'),
        ),
        migrations.AlterField(
            model_name='calenderevent',
            name='event_date',
            field=models.DateField(default=datetime.date.today, verbose_name='datum'),
        ),
        migrations.AlterField(
            model_name='calenderevent',
            name='name',
            field=models.CharField(max_length=164, verbose_name='naam'),
        ),
    ]
