# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-29 08:53
from __future__ import unicode_literals

from django.db import migrations, models
import home.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20161029_0813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customimage',
            name='file',
            field=models.ImageField(height_field='height', upload_to=home.models.get_upload_to, verbose_name='file', width_field='width'),
        ),
    ]
