# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-09 15:59
from __future__ import unicode_literals

from django.db import migrations
import home.blocks
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_auto_20161109_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='blog_content',
            field=wagtail.wagtailcore.fields.StreamField((('blog_intro', home.blocks.IntroTextBlock(help_text='Hiermee kan je optioneel een korte inleiding voorzien')), ('blog_subtitle', home.blocks.SubtitleBlock()), ('blog_paragraph', home.blocks.ParagraphBlock()), ('blog_image', wagtail.wagtailcore.blocks.StructBlock(())), ('blog_quote', wagtail.wagtailcore.blocks.StructBlock((('quote', wagtail.wagtailcore.blocks.CharBlock(help_text='Geef hier een citaat in', label='Citaat', max_length=164, required=True)),)))), verbose_name='Blog Inhoud'),
        ),
    ]
