# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-15 19:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0029_partner_logo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='partner',
            options={'ordering': ['name'], 'verbose_name': 'partner', 'verbose_name_plural': 'partners'},
        ),
        migrations.AddField(
            model_name='homepage',
            name='catchphrase',
            field=models.CharField(default='Entertainment voor jongeren', max_length=164, verbose_name='catchphrase'),
        ),
    ]
