# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-15 19:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0030_auto_20161115_1901'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutpage',
            name='catchphrase',
            field=models.CharField(default='Entertainment voor jongeren', max_length=164, verbose_name='catchphrase'),
        ),
        migrations.AddField(
            model_name='blog',
            name='catchphrase',
            field=models.CharField(default='Entertainment voor jongeren', max_length=164, verbose_name='catchphrase'),
        ),
        migrations.AddField(
            model_name='blogindex',
            name='catchphrase',
            field=models.CharField(default='Entertainment voor jongeren', max_length=164, verbose_name='catchphrase'),
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='catchphrase',
            field=models.CharField(default='Entertainment voor jongeren', max_length=164, verbose_name='catchphrase'),
        ),
        migrations.AddField(
            model_name='calendarindex',
            name='catchphrase',
            field=models.CharField(default='Entertainment voor jongeren', max_length=164, verbose_name='catchphrase'),
        ),
        migrations.AddField(
            model_name='calendarpage',
            name='catchphrase',
            field=models.CharField(default='Entertainment voor jongeren', max_length=164, verbose_name='catchphrase'),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='catchphrase',
            field=models.CharField(default='Entertainment voor jongeren', max_length=164, verbose_name='catchphrase'),
        ),
        migrations.AddField(
            model_name='event',
            name='catchphrase',
            field=models.CharField(default='Entertainment voor jongeren', max_length=164, verbose_name='catchphrase'),
        ),
        migrations.AddField(
            model_name='eventindex',
            name='catchphrase',
            field=models.CharField(default='Entertainment voor jongeren', max_length=164, verbose_name='catchphrase'),
        ),
        migrations.AddField(
            model_name='influencer',
            name='catchphrase',
            field=models.CharField(default='Entertainment voor jongeren', max_length=164, verbose_name='catchphrase'),
        ),
        migrations.AddField(
            model_name='influencerindex',
            name='catchphrase',
            field=models.CharField(default='Entertainment voor jongeren', max_length=164, verbose_name='catchphrase'),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='catchphrase',
            field=models.CharField(default='Entertainment voor jongeren', max_length=164, verbose_name='catchphrase'),
        ),
    ]
