# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-18 14:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0037_influencer_influencerrelatedlink'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='influencer',
            name='catchphrase',
        ),
    ]
