# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-18 14:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0040_auto_20161118_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='influencer',
            name='extra_info',
            field=models.TextField(null=True, verbose_name='Beschrijving'),
        ),
    ]
