# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-18 15:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0043_auto_20161118_1434'),
    ]

    operations = [
        migrations.AddField(
            model_name='influencerrelatedlink',
            name='icon_class',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
