# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-23 13:58
from __future__ import unicode_literals

from django.db import migrations
import home.blocks
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0048_auto_20161123_1045'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EventCategory',
            new_name='Category',
        ),
        migrations.AlterModelOptions(
            name='whatwedo',
            options={'verbose_name': 'homepage pijler', 'verbose_name_plural': 'homepage pijlers'},
        ),
        migrations.AlterField(
            model_name='blog',
            name='blog_content',
            field=wagtail.wagtailcore.fields.StreamField((('blog_paragraph', home.blocks.ParagraphBlock()), ('blog_image', wagtail.wagtailcore.blocks.StructBlock(())), ('blog_quote', wagtail.wagtailcore.blocks.StructBlock((('quote', wagtail.wagtailcore.blocks.CharBlock(help_text='Geef hier een citaat in', label='Citaat', max_length=164, required=True)),)))), verbose_name='Blog Inhoud'),
        ),
    ]
