# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-23 14:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0049_auto_20161123_1358'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventCategory',
            fields=[
                ('category_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='home.Category')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='home.Event')),
            ],
            bases=('home.category',),
        ),
    ]
