# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-23 14:30
from __future__ import unicode_literals

from django.db import migrations
import modelcluster.contrib.taggit


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        ('wagtailforms', '0003_capitalizeverbose'),
        ('wagtailredirects', '0005_capitalizeverbose'),
        ('wagtailcore', '0030_index_on_pagerevision_created_at'),
        ('home', '0052_auto_20161123_1418'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsarticle',
            name='image',
        ),
        migrations.RemoveField(
            model_name='newsarticle',
            name='page_ptr',
        ),
        migrations.AddField(
            model_name='blog',
            name='tags',
            field=modelcluster.contrib.taggit.ClusterTaggableManager(blank=True, help_text='A comma-separated list of tags.', through='home.EventTag', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.DeleteModel(
            name='NewsArticle',
        ),
    ]
