# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-23 18:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0030_index_on_pagerevision_created_at'),
        ('home', '0057_auto_20161123_1858'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatWeDo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='naam')),
                ('extra_info', models.TextField(max_length=512, verbose_name='info tekst')),
            ],
            options={
                'verbose_name': 'homepage pijler',
                'verbose_name_plural': 'homepage pijlers',
            },
        ),
        migrations.CreateModel(
            name='HomePageContent',
            fields=[
                ('whatwedo_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='home.WhatWeDo')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='content', to='home.HomePage')),
            ],
            options={
                'abstract': False,
                'ordering': ['sort_order'],
            },
            bases=('home.whatwedo', models.Model),
        ),
        migrations.AddField(
            model_name='whatwedo',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='home.CustomImage', verbose_name='afbeelding'),
        ),
        migrations.AddField(
            model_name='whatwedo',
            name='related_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.Page', verbose_name='Link naar pagina'),
        ),
    ]
