# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-24 09:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0061_auto_20161124_0918'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePageNumbers',
            fields=[
                ('numbers_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='home.Numbers')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='numbers', to='home.HomePage')),
            ],
            options={
                'abstract': False,
                'ordering': ['sort_order'],
            },
            bases=('home.numbers', models.Model),
        ),
        migrations.AddField(
            model_name='numbers',
            name='icon',
            field=models.CharField(choices=[('bar-chart', 'Grafiek'), ('car', 'Auto'), ('battery-3', 'Batterij'), ('bolt', 'Bliksem'), ('bomb', 'Bom'), ('calendar', 'kalender'), ('camera', 'Fototoestel'), ('child', 'Link'), ('cloud', 'Wolk'), ('commenting-o', 'Tekstballon'), ('exclamation', 'Uitroepteken'), ('flag', 'Vlag'), ('gift', 'Geschenk'), ('group', 'Groep mensen'), ('glass', 'Glas'), ('home', 'Home'), ('heart-o', 'Hart'), ('cutlery', 'Bestek'), ('globe', 'Wereldbol'), ('hashtag', 'Hashtag'), ('key', 'Sleutel'), ('magic', 'Toverstaf'), ('microphone', 'Microfoon'), ('mobile', 'GSM'), ('paint-brush', 'Penceel'), ('pencil', 'Potlood'), ('quote-right', 'Aanhalingstekens'), ('shopping-basket', 'Mandje'), ('star', 'Ster'), ('user', 'Gebruiker'), ('video-camera', 'Camera')], default='bar-chart', max_length=28, verbose_name='icoon'),
        ),
        migrations.AddField(
            model_name='numbers',
            name='icon_color',
            field=models.CharField(choices=[('text-default', 'Zwart'), ('text-gray', 'Lichtgijs'), ('text-primary', 'Groen'), ('text-deluge', 'Paars'), ('text-piction-blue', 'Blauw'), ('text-mantis', 'Lichtgroen'), ('text-malibu', 'Lichtblauw'), ('text-carrot', 'Oranje'), ('text-red', 'Rood'), ('text-blue-gray', 'Paars-blauw'), ('text-pink', 'Donkerpaars')], default='text-default', max_length=32, verbose_name='kleur icoon'),
        ),
    ]
