# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-30 09:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0074_homepage_intro_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blog_images', to='home.CustomImage', verbose_name='afbeelding'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='intro_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='home_intro_images', to='home.CustomImage'),
        ),
    ]
