# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-30 11:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0079_auto_20161130_1104'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=40, verbose_name='stad')),
                ('postal_code', models.CharField(max_length=8, verbose_name='postcode')),
                ('street', models.CharField(max_length=40, verbose_name='straat')),
                ('number', models.CharField(max_length=8, verbose_name='nummer')),
                ('country', django_countries.fields.CountryField(default='BE', max_length=2, null=True, verbose_name='land')),
            ],
            options={
                'verbose_name': 'adres',
                'verbose_name_plural': 'adressen',
                'ordering': ['city'],
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('address_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='home.Address')),
                ('name', models.CharField(max_length=64)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
            ],
            options={
                'verbose_name': 'locatie',
                'verbose_name_plural': 'locaties',
                'ordering': ['name'],
            },
            bases=('home.address',),
        ),
    ]
