# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-03 11:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0085_contactpage_intro_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutpage',
            name='fb_link',
            field=models.URLField(default='https://www.facebook.com/yourin.be/', verbose_name='FB pagina'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='linkedin_link',
            field=models.URLField(default='https://www.linkedin.com/company/4982091', verbose_name='LinkedIn pagina'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='twitter_link',
            field=models.URLField(default='https://twitter.com/yourinbe', verbose_name='Twitter pagina'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='youtube_link',
            field=models.URLField(default='https://www.youtube.com/user/yourinbe', verbose_name='Youtube kanaal'),
        ),
        migrations.AddField(
            model_name='blog',
            name='fb_link',
            field=models.URLField(default='https://www.facebook.com/yourin.be/', verbose_name='FB pagina'),
        ),
        migrations.AddField(
            model_name='blog',
            name='linkedin_link',
            field=models.URLField(default='https://www.linkedin.com/company/4982091', verbose_name='LinkedIn pagina'),
        ),
        migrations.AddField(
            model_name='blog',
            name='twitter_link',
            field=models.URLField(default='https://twitter.com/yourinbe', verbose_name='Twitter pagina'),
        ),
        migrations.AddField(
            model_name='blog',
            name='youtube_link',
            field=models.URLField(default='https://www.youtube.com/user/yourinbe', verbose_name='Youtube kanaal'),
        ),
        migrations.AddField(
            model_name='blogindex',
            name='fb_link',
            field=models.URLField(default='https://www.facebook.com/yourin.be/', verbose_name='FB pagina'),
        ),
        migrations.AddField(
            model_name='blogindex',
            name='linkedin_link',
            field=models.URLField(default='https://www.linkedin.com/company/4982091', verbose_name='LinkedIn pagina'),
        ),
        migrations.AddField(
            model_name='blogindex',
            name='twitter_link',
            field=models.URLField(default='https://twitter.com/yourinbe', verbose_name='Twitter pagina'),
        ),
        migrations.AddField(
            model_name='blogindex',
            name='youtube_link',
            field=models.URLField(default='https://www.youtube.com/user/yourinbe', verbose_name='Youtube kanaal'),
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='fb_link',
            field=models.URLField(default='https://www.facebook.com/yourin.be/', verbose_name='FB pagina'),
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='linkedin_link',
            field=models.URLField(default='https://www.linkedin.com/company/4982091', verbose_name='LinkedIn pagina'),
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='twitter_link',
            field=models.URLField(default='https://twitter.com/yourinbe', verbose_name='Twitter pagina'),
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='youtube_link',
            field=models.URLField(default='https://www.youtube.com/user/yourinbe', verbose_name='Youtube kanaal'),
        ),
        migrations.AddField(
            model_name='calendarindex',
            name='fb_link',
            field=models.URLField(default='https://www.facebook.com/yourin.be/', verbose_name='FB pagina'),
        ),
        migrations.AddField(
            model_name='calendarindex',
            name='linkedin_link',
            field=models.URLField(default='https://www.linkedin.com/company/4982091', verbose_name='LinkedIn pagina'),
        ),
        migrations.AddField(
            model_name='calendarindex',
            name='twitter_link',
            field=models.URLField(default='https://twitter.com/yourinbe', verbose_name='Twitter pagina'),
        ),
        migrations.AddField(
            model_name='calendarindex',
            name='youtube_link',
            field=models.URLField(default='https://www.youtube.com/user/yourinbe', verbose_name='Youtube kanaal'),
        ),
        migrations.AddField(
            model_name='calendarpage',
            name='fb_link',
            field=models.URLField(default='https://www.facebook.com/yourin.be/', verbose_name='FB pagina'),
        ),
        migrations.AddField(
            model_name='calendarpage',
            name='linkedin_link',
            field=models.URLField(default='https://www.linkedin.com/company/4982091', verbose_name='LinkedIn pagina'),
        ),
        migrations.AddField(
            model_name='calendarpage',
            name='twitter_link',
            field=models.URLField(default='https://twitter.com/yourinbe', verbose_name='Twitter pagina'),
        ),
        migrations.AddField(
            model_name='calendarpage',
            name='youtube_link',
            field=models.URLField(default='https://www.youtube.com/user/yourinbe', verbose_name='Youtube kanaal'),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='fb_link',
            field=models.URLField(default='https://www.facebook.com/yourin.be/', verbose_name='FB pagina'),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='linkedin_link',
            field=models.URLField(default='https://www.linkedin.com/company/4982091', verbose_name='LinkedIn pagina'),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='twitter_link',
            field=models.URLField(default='https://twitter.com/yourinbe', verbose_name='Twitter pagina'),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='youtube_link',
            field=models.URLField(default='https://www.youtube.com/user/yourinbe', verbose_name='Youtube kanaal'),
        ),
        migrations.AddField(
            model_name='event',
            name='fb_link',
            field=models.URLField(default='https://www.facebook.com/yourin.be/', verbose_name='FB pagina'),
        ),
        migrations.AddField(
            model_name='event',
            name='linkedin_link',
            field=models.URLField(default='https://www.linkedin.com/company/4982091', verbose_name='LinkedIn pagina'),
        ),
        migrations.AddField(
            model_name='event',
            name='twitter_link',
            field=models.URLField(default='https://twitter.com/yourinbe', verbose_name='Twitter pagina'),
        ),
        migrations.AddField(
            model_name='event',
            name='youtube_link',
            field=models.URLField(default='https://www.youtube.com/user/yourinbe', verbose_name='Youtube kanaal'),
        ),
        migrations.AddField(
            model_name='eventindex',
            name='fb_link',
            field=models.URLField(default='https://www.facebook.com/yourin.be/', verbose_name='FB pagina'),
        ),
        migrations.AddField(
            model_name='eventindex',
            name='linkedin_link',
            field=models.URLField(default='https://www.linkedin.com/company/4982091', verbose_name='LinkedIn pagina'),
        ),
        migrations.AddField(
            model_name='eventindex',
            name='twitter_link',
            field=models.URLField(default='https://twitter.com/yourinbe', verbose_name='Twitter pagina'),
        ),
        migrations.AddField(
            model_name='eventindex',
            name='youtube_link',
            field=models.URLField(default='https://www.youtube.com/user/yourinbe', verbose_name='Youtube kanaal'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='fb_link',
            field=models.URLField(default='https://www.facebook.com/yourin.be/', verbose_name='FB pagina'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='linkedin_link',
            field=models.URLField(default='https://www.linkedin.com/company/4982091', verbose_name='LinkedIn pagina'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='twitter_link',
            field=models.URLField(default='https://twitter.com/yourinbe', verbose_name='Twitter pagina'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='youtube_link',
            field=models.URLField(default='https://www.youtube.com/user/yourinbe', verbose_name='Youtube kanaal'),
        ),
        migrations.AddField(
            model_name='influencer',
            name='fb_link',
            field=models.URLField(default='https://www.facebook.com/yourin.be/', verbose_name='FB pagina'),
        ),
        migrations.AddField(
            model_name='influencer',
            name='linkedin_link',
            field=models.URLField(default='https://www.linkedin.com/company/4982091', verbose_name='LinkedIn pagina'),
        ),
        migrations.AddField(
            model_name='influencer',
            name='twitter_link',
            field=models.URLField(default='https://twitter.com/yourinbe', verbose_name='Twitter pagina'),
        ),
        migrations.AddField(
            model_name='influencer',
            name='youtube_link',
            field=models.URLField(default='https://www.youtube.com/user/yourinbe', verbose_name='Youtube kanaal'),
        ),
        migrations.AddField(
            model_name='influencerindex',
            name='fb_link',
            field=models.URLField(default='https://www.facebook.com/yourin.be/', verbose_name='FB pagina'),
        ),
        migrations.AddField(
            model_name='influencerindex',
            name='linkedin_link',
            field=models.URLField(default='https://www.linkedin.com/company/4982091', verbose_name='LinkedIn pagina'),
        ),
        migrations.AddField(
            model_name='influencerindex',
            name='twitter_link',
            field=models.URLField(default='https://twitter.com/yourinbe', verbose_name='Twitter pagina'),
        ),
        migrations.AddField(
            model_name='influencerindex',
            name='youtube_link',
            field=models.URLField(default='https://www.youtube.com/user/yourinbe', verbose_name='Youtube kanaal'),
        ),
        migrations.AlterField(
            model_name='contactpage',
            name='intro_text',
            field=models.CharField(default='Vivamus sagittis lacus vel augue laoreet rutrum faucibus \n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tdolor auctor. Cras justo odio, dapibus ac facilisis in, egestas \n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\teget quam. Cras mattis consectetur purus sit amet fermentum.', max_length=255),
        ),
    ]
