# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-09 07:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.contrib.taggit


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        ('wagtailcore', '0030_index_on_pagerevision_created_at'),
        ('home', '0089_auto_20161208_2022'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventGroup',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('name', models.CharField(blank=True, default='', max_length=164, null=True, verbose_name='naam')),
                ('description', models.TextField(null=True, verbose_name='beschrijving')),
                ('website', models.URLField(null=True, verbose_name='website ')),
                ('class_name', models.CharField(default='cal_event', max_length=28)),
                ('category', models.PositiveIntegerField(choices=[(1, 'Sport'), (2, 'Kamp'), (3, 'Festival'), (4, 'Club')], default=1)),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='home.CustomImage', verbose_name='logo')),
                ('tags', modelcluster.contrib.taggit.ClusterTaggableManager(blank=True, help_text='A comma-separated list of tags.', through='home.EventTag', to='taggit.Tag', verbose_name='Tags')),
            ],
            options={
                'verbose_name': 'event groepen',
            },
            bases=('wagtailcore.page',),
        ),
    ]
