# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-09 07:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0091_eventinstance'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventEventInstance',
            fields=[
                ('eventinstance_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='home.EventInstance')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='home.Event')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
            bases=('home.eventinstance', models.Model),
        ),
    ]
