# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-09 18:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0094_auto_20161209_0756'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='subtitle',
            field=models.CharField(max_length=120, null=True, verbose_name='korte intro'),
        ),
    ]
