# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-09 18:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0095_event_subtitle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='subtitle',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='korte intro'),
        ),
    ]
