# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-11 18:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0098_auto_20161211_1829'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventinstance',
            name='image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.CustomImage'),
        ),
    ]
