# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-13 15:42
from __future__ import unicode_literals

from django.db import migrations, models
import home.blocks
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0099_eventinstance_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutpage',
            options={'verbose_name': 'over ons pagina', 'verbose_name_plural': "over ons pagina's"},
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='edited',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='page_content',
            field=wagtail.wagtailcore.fields.StreamField((('subtitle', home.blocks.SubtitleBlock()), ('paragraph', home.blocks.ParagraphBlock()), ('image', wagtail.wagtailcore.blocks.StructBlock(())), ('quote', wagtail.wagtailcore.blocks.StructBlock((('quote', wagtail.wagtailcore.blocks.CharBlock(help_text='Geef hier een citaat in', label='Citaat', max_length=164, required=True)),))), ('video', home.blocks.BlogEmbedBlock())), null=True, verbose_name='Over ons pagina - inhoud'),
        ),
    ]
