# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-13 18:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import home.blocks
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0030_index_on_pagerevision_created_at'),
        ('home', '0101_homepage_catchphrase_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='DynamicPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('page_content', wagtail.wagtailcore.fields.StreamField((('subtitle', home.blocks.SubtitleBlock()), ('paragraph', home.blocks.ParagraphBlock()), ('image', wagtail.wagtailcore.blocks.StructBlock(())), ('quote', wagtail.wagtailcore.blocks.StructBlock((('quote', wagtail.wagtailcore.blocks.CharBlock(help_text='Geef hier een citaat in', label='Citaat', max_length=164, required=True)),))), ('video', home.blocks.BlogEmbedBlock())), null=True, verbose_name='Over ons pagina - inhoud')),
            ],
            options={
                'verbose_name_plural': "dynamische pagina's",
                'verbose_name': 'dynamische pagina',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='catchphrase_color',
            field=models.CharField(choices=[('text-default', 'Wit'), ('text-gray', 'Lichtgijs'), ('text-primary', 'Yourin Rood'), ('text-deluge', 'Paars'), ('text-piction-blue', 'Blauw'), ('text-mantis', 'Rood-oranje'), ('text-malibu', 'Lichtblauw'), ('text-carrot', 'Oranje'), ('text-red', 'Fel Rood'), ('text-blue-gray', 'Paars-blauw'), ('text-pink', 'Donkerpaars'), ('text-green', 'Groen'), ('text-yellow', 'Geel')], default='text-default', max_length=32, verbose_name='catchphrase kleur'),
        ),
        migrations.AlterField(
            model_name='numbers',
            name='icon_color',
            field=models.CharField(choices=[('text-default', 'Wit'), ('text-gray', 'Lichtgijs'), ('text-primary', 'Yourin Rood'), ('text-deluge', 'Paars'), ('text-piction-blue', 'Blauw'), ('text-mantis', 'Rood-oranje'), ('text-malibu', 'Lichtblauw'), ('text-carrot', 'Oranje'), ('text-red', 'Fel Rood'), ('text-blue-gray', 'Paars-blauw'), ('text-pink', 'Donkerpaars'), ('text-green', 'Groen'), ('text-yellow', 'Geel')], default='text-default', max_length=32, verbose_name='kleur icoon'),
        ),
    ]
