# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-24 19:15
from __future__ import unicode_literals

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0030_index_on_pagerevision_created_at'),
        ('home', '0002_create_homepage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=40, verbose_name='stad')),
                ('postal_code', models.CharField(max_length=8, null=True, verbose_name='postcode')),
                ('street', models.CharField(max_length=40, null=True, verbose_name='straat')),
                ('number', models.CharField(max_length=8, null=True, verbose_name='nummer')),
                ('country', django_countries.fields.CountryField(default='BE', max_length=2, null=True, verbose_name='land')),
            ],
        ),
        migrations.CreateModel(
            name='CalenderEvent',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('name', models.CharField(max_length=164)),
                ('description', models.TextField()),
                ('event_date', models.DateField(default=datetime.date.today)),
                ('event_duration', models.PositiveIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(21)], verbose_name='Duur (# dagen)')),
                ('website', models.URLField()),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='location', to='home.Address', verbose_name='adres')),
            ],
        ),
    ]
