# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-14 18:44
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_address_calenderevent_location_squashed_0105_auto_20161214_1714'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutpage',
            name='intro',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True, null=True, verbose_name='inhoud - alternatief'),
        ),
    ]
