# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-15 18:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_whatwedo_text_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutpage',
            name='has_subtitle',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='has_subtitle',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='blogindex',
            name='has_subtitle',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='has_subtitle',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='calendarindex',
            name='has_subtitle',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='calendarpage',
            name='has_subtitle',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='has_subtitle',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='dynamicpage',
            name='has_subtitle',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='event',
            name='has_subtitle',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='eventindex',
            name='has_subtitle',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='has_subtitle',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='influencer',
            name='has_subtitle',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='influencerindex',
            name='has_subtitle',
            field=models.BooleanField(default=True),
        ),
    ]
