# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-15 18:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20161215_1830'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactpage',
            name='address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.Location', verbose_name='locatie'),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='phone',
            field=models.CharField(blank=True, max_length=28, null=True, verbose_name='telefoonnr'),
        ),
        migrations.AlterField(
            model_name='eventinstance',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.Location', verbose_name='locatie'),
        ),
    ]
