# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-15 18:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20161215_1847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactpage',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.Location', verbose_name='locatie'),
        ),
    ]
