# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-15 18:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20161215_1849'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactpage',
            name='address',
        ),
    ]
