# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-15 19:23
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_remove_contactpage_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='intro',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True, null=True, verbose_name='beschrijving(alternatief)'),
        ),
    ]
