# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-18 09:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_auto_20161218_0850'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventInstanceImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(blank=True, max_length=63, null=True)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.CustomImage')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='picture',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='home.CustomImage', verbose_name='foto'),
        ),
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='home.CustomImage', verbose_name='logo'),
        ),
    ]
