# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-01 19:36
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_remove_blog_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogindex',
            name='intro',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True),
        ),
    ]
