# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-19 20:10
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_auto_20161219_1945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutpage',
            name='intro',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True, null=True, verbose_name='inhoud (Alternatief)'),
        ),
    ]
