# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-08 14:08
from __future__ import unicode_literals

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_auto_20161108_1352'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='home.EventCategory'),
        ),
        migrations.AddField(
            model_name='event',
            name='description',
            field=models.TextField(null=True, verbose_name='beschrijving'),
        ),
        migrations.AddField(
            model_name='event',
            name='event_date',
            field=models.DateField(default=datetime.date.today, verbose_name='datum'),
        ),
        migrations.AddField(
            model_name='event',
            name='event_duration',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(21)], verbose_name='Duur (# dagen)'),
        ),
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='home.CustomImage'),
        ),
        migrations.AddField(
            model_name='event',
            name='name',
            field=models.CharField(default='', max_length=164, verbose_name='naam'),
        ),
        migrations.AddField(
            model_name='event',
            name='website',
            field=models.URLField(null=True, verbose_name='event website'),
        ),
        migrations.AlterField(
            model_name='calendarevent',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calendar_events', to='home.EventCategory'),
        ),
    ]
