# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-09 12:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_auto_20161108_1408'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventindex',
            name='name',
            field=models.CharField(default='', max_length=164, verbose_name='naam'),
        ),
    ]
