# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-09 14:52
from __future__ import unicode_literals

from django.db import migrations, models
import home.blocks
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields
import wagtail.wagtailimages.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_eventindex_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='edited',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='blog_content',
            field=wagtail.wagtailcore.fields.StreamField((('blog_title', wagtail.wagtailcore.blocks.StructBlock((('image', wagtail.wagtailimages.blocks.ImageChooserBlock(label='afbeelding', required=True)), ('title', wagtail.wagtailcore.blocks.CharBlock(label='titel', required=True))), help_text='Dit is de titel van het artikel, voorzien van een afbeelding')), ('blog_intro', home.blocks.IntroTextBlock(help_text='Hiermee kan je optioneel een korte inleiding voorzien')), ('blog_subtitle', home.blocks.SubtitleBlock()), ('blog_paragraph', home.blocks.ParagraphBlock()), ('blog_image', wagtail.wagtailcore.blocks.StructBlock(())), ('blog_quote', wagtail.wagtailcore.blocks.StructBlock((('quote', wagtail.wagtailcore.blocks.CharBlock(help_text='Geef hier een citaat in', label='Citaat', max_length=164, required=True)),)))), verbose_name='Blog Inhoud'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
