# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-21 10:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_auto_20161220_1916'),
    ]

    operations = [
        migrations.AddField(
            model_name='influencer',
            name='num_followers',
            field=models.PositiveIntegerField(default=1, verbose_name='# volgers'),
        ),
    ]
