# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-27 18:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0033_auto_20161218_0850'),
        #('home', '0024_influencer_num_followers'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventInstancePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('has_subtitle', models.BooleanField(default=True, verbose_name='Subtitel balk')),
                ('event_description', wagtail.wagtailcore.fields.RichTextField(null=True, verbose_name='beschrijving')),
                ('website', models.URLField(blank=True, null=True, verbose_name='website URL')),
                ('intro', wagtail.wagtailcore.fields.RichTextField(blank=True, null=True, verbose_name='inhoud (Alternatief)')),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.Location', verbose_name='locatie')),
            ],
            options={
                'verbose_name': 'evenement',
                'verbose_name_plural': 'evenementen',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='EventInstancePageImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='home.CustomImage')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='home.EventInstancePage')),
            ],
            options={
                'abstract': False,
                'ordering': ['sort_order'],
            },
        ),
        migrations.AlterModelOptions(
            name='yourinpartner',
            options={'ordering': ['sort_order']},
        ),
        migrations.AddField(
            model_name='yourinpartner',
            name='sort_order',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
    ]
