# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-10 09:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_auto_20161109_1707'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partners',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='naam')),
                ('website', models.URLField(verbose_name='website')),
                ('description', models.TextField(verbose_name='beschrijving')),
            ],
        ),
    ]
