# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-10 09:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_partners'),
    ]

    operations = [
        migrations.CreateModel(
            name='YourinPartner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='partners', to='home.HomePage')),
            ],
        ),
        migrations.RenameModel(
            old_name='Partners',
            new_name='Partner',
        ),
        migrations.AddField(
            model_name='yourinpartner',
            name='partner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Partner'),
        ),
    ]
