# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-28 17:39
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0028_homepagerecents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepagerecents',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='recent_items', to='home.HomePage'),
        ),
    ]
