# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-28 17:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0029_auto_20161228_1739'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventinstancepage',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='home.CustomImage', verbose_name='afbeelding'),
        ),
    ]
