# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-28 18:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0031_homepagerecents_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepagerecents',
            name='info',
            field=models.CharField(max_length=263, null=True),
        ),
    ]
