# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-15 19:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0031_auto_20161115_1926'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePageNumbers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=28, verbose_name='naam')),
                ('value', models.PositiveIntegerField(default=1, verbose_name='aantal')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='yourinpartner',
            unique_together=set([('page', 'partner')]),
        ),
    ]
