# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-15 19:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0032_auto_20161115_1950'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='yourinpartner',
            unique_together=set([]),
        ),
    ]
