# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-18 13:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0030_index_on_pagerevision_created_at'),
        ('wagtailforms', '0003_capitalizeverbose'),
        ('wagtailredirects', '0005_capitalizeverbose'),
        ('home', '0035_influencerrelatedlink'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='influencer',
            name='page_ptr',
        ),
        migrations.RemoveField(
            model_name='influencerrelatedlink',
            name='link_page',
        ),
        migrations.RemoveField(
            model_name='influencerrelatedlink',
            name='page',
        ),
        migrations.DeleteModel(
            name='Influencer',
        ),
        migrations.DeleteModel(
            name='InfluencerRelatedLink',
        ),
    ]
