# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-04 19:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0037_contactpageformfield'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactpage',
            name='thank_you_text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
