# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-18 14:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0038_remove_influencer_catchphrase'),
    ]

    operations = [
        migrations.AddField(
            model_name='influencer',
            name='catchphrase',
            field=models.CharField(default='Entertainment voor jongeren', max_length=164, verbose_name='catchphrase'),
        ),
    ]
