# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-05 19:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0038_contactpage_thank_you_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=63, verbose_name='name')),
                ('role', models.CharField(max_length=63, verbose_name='functie')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
            ],
            options={
                'verbose_name': 'teamlid',
                'verbose_name_plural': 'teamleden',
            },
        ),
        migrations.AlterModelOptions(
            name='contactpage',
            options={'verbose_name': 'Contact Pagina', 'verbose_name_plural': "Contact Pagina's"},
        ),
        migrations.AlterField(
            model_name='contactpage',
            name='thank_you_text',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Bedankt tekstje'),
        ),
        migrations.CreateModel(
            name='AboutPageTeamMember',
            fields=[
                ('teammember_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='home.TeamMember')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='teammembers', to='home.AboutPage')),
            ],
            options={
                'abstract': False,
                'ordering': ['sort_order'],
            },
            bases=('home.teammember', models.Model),
        ),
        migrations.AddField(
            model_name='teammember',
            name='image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='home.CustomImage', verbose_name='afbeelding'),
        ),
    ]
