# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-20 18:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0039_auto_20170105_1918'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customrendition',
            name='filter',
        ),
        migrations.AlterField(
            model_name='contactpage',
            name='email',
            field=models.EmailField(default='info@yourin.be', max_length=254, verbose_name='contact email'),
        ),
        migrations.AlterField(
            model_name='customrendition',
            name='focal_point_key',
            field=models.CharField(blank=True, default='', editable=False, max_length=16),
        ),
    ]
