# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-18 14:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0039_influencer_catchphrase'),
    ]

    operations = [
        migrations.AddField(
            model_name='influencer',
            name='extra_info',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='influencer',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='home.CustomImage', verbose_name='afbeelding'),
        ),
    ]
