# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-22 19:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0044_influencerrelatedlink_icon_class'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventindex',
            name='name',
        ),
    ]
