# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-22 19:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0046_auto_20161122_1953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.CharField(blank=True, default='', max_length=164, null=True, verbose_name='naam'),
        ),
    ]
