# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-23 10:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0047_auto_20161122_1954'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='class_name',
            field=models.CharField(default='cal_blog', max_length=28),
        ),
        migrations.AddField(
            model_name='event',
            name='class_name',
            field=models.CharField(default='cal_event', max_length=28),
        ),
    ]
