# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-24 08:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0058_auto_20161123_1859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whatwedo',
            name='extra_info',
            field=models.TextField(blank=True, max_length=512, null=True, verbose_name='info tekst'),
        ),
    ]
