# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-24 09:00
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0059_auto_20161124_0853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepagecontent',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='home.HomePage'),
        ),
    ]
