# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-24 16:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0066_auto_20161124_1604'),
    ]

    operations = [
        migrations.AddField(
            model_name='influencer',
            name='quote',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Influencer citaat'),
        ),
    ]
