# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-25 18:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0067_influencer_quote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='image',
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[(1, 'Sport'), (2, 'Kamp'), (3, 'Festival'), (4, 'Club')], max_length=64, verbose_name='categorie'),
        ),
    ]
