# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-30 10:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0075_auto_20161130_0902'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.Location', verbose_name='event locatie'),
        ),
    ]
