# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-30 10:57
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0077_auto_20161130_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventlocation',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='home.Event'),
        ),
    ]
