# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-03 10:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0083_contactpage_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactpage',
            name='email',
            field=models.EmailField(default='ditishet_emailadresvoor@contactformulier.website', max_length=254, verbose_name='contact email'),
        ),
    ]
