# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-08 15:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0088_auto_20161203_1145'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'verbose_name': 'event groepen'},
        ),
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='home.CustomImage', verbose_name='logo'),
        ),
        migrations.AlterField(
            model_name='event',
            name='website',
            field=models.URLField(null=True, verbose_name='website '),
        ),
        migrations.AlterField(
            model_name='numbers',
            name='icon_color',
            field=models.CharField(choices=[('text-default', 'Wit'), ('text-gray', 'Lichtgijs'), ('text-primary', 'Yourin Rood'), ('text-deluge', 'Paars'), ('text-piction-blue', 'Blauw'), ('text-mantis', 'Lichtgroen'), ('text-malibu', 'Lichtblauw'), ('text-carrot', 'Oranje'), ('text-red', 'Fel Rood'), ('text-blue-gray', 'Paars-blauw'), ('text-pink', 'Donkerpaars')], default='text-default', max_length=32, verbose_name='kleur icoon'),
        ),
    ]
