# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-08 15:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0089_auto_20161208_1531'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Event',
            new_name='EventGroup',
        ),
    ]
