# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-08 15:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.contrib.taggit
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        ('home', '0090_auto_20161208_1535'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventGroupTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RenameModel(
            old_name='EventCategory',
            new_name='EventGroupCategory',
        ),
        migrations.RenameModel(
            old_name='EventLocation',
            new_name='EventGroupLocation',
        ),
        migrations.RemoveField(
            model_name='eventtag',
            name='content_object',
        ),
        migrations.RemoveField(
            model_name='eventtag',
            name='tag',
        ),
        migrations.AlterField(
            model_name='eventgroup',
            name='tags',
            field=modelcluster.contrib.taggit.ClusterTaggableManager(blank=True, help_text='A comma-separated list of tags.', through='home.EventGroupTag', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.DeleteModel(
            name='EventTag',
        ),
        migrations.AddField(
            model_name='eventgrouptag',
            name='content_object',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagged_items', to='home.EventGroup'),
        ),
        migrations.AddField(
            model_name='eventgrouptag',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_eventgrouptag_items', to='taggit.Tag'),
        ),
    ]
