# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-09 07:42
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0090_eventgroup'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=128, verbose_name='naam')),
                ('event_description', models.TextField(null=True, verbose_name='beschrijving')),
                ('event_date', models.DateField(default=datetime.date.today, verbose_name='datum')),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.Location')),
            ],
        ),
    ]
