# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-08 17:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0092_auto_20161208_1555'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('location_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='home.Location')),
                ('event_name', models.CharField(max_length=128, verbose_name='event naam')),
                ('event_date', models.DateField(auto_now=True, verbose_name='event datum')),
            ],
            bases=('home.location',),
        ),
        migrations.CreateModel(
            name='EventGroupEvent',
            fields=[
                ('location_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='home.Location')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='home.EventGroup')),
            ],
            options={
                'abstract': False,
                'ordering': ['sort_order'],
            },
            bases=('home.location', models.Model),
        ),
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(max_length=64, verbose_name='naam locatie'),
        ),
    ]
