# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-08 18:00
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0093_auto_20161208_1754'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventgroupevent',
            name='location_ptr',
        ),
        migrations.AddField(
            model_name='eventgroupevent',
            name='event_ptr',
            field=models.OneToOneField(auto_created=True, default=500, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='home.Event'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='event_date',
            field=models.DateField(default=datetime.date.today, verbose_name='event datum'),
        ),
    ]
