# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-09 07:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0093_auto_20161209_0744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventinstance',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.Location', verbose_name='location'),
        ),
    ]
