# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-13 16:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0100_auto_20161213_1542'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='catchphrase_color',
            field=models.CharField(choices=[('text-default', 'Wit'), ('text-gray', 'Lichtgijs'), ('text-primary', 'Yourin Rood'), ('text-deluge', 'Paars'), ('text-piction-blue', 'Blauw'), ('text-mantis', 'Lichtgroen'), ('text-malibu', 'Lichtblauw'), ('text-carrot', 'Oranje'), ('text-red', 'Fel Rood'), ('text-blue-gray', 'Paars-blauw'), ('text-pink', 'Donkerpaars')], default='text-default', max_length=32, verbose_name='kleur icoon'),
        ),
    ]
