# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-14 17:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0104_auto_20161213_1926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='catchphrase_color',
            field=models.CharField(choices=[('text-default', 'Wit'), ('text-black', 'Zwart'), ('text-gray', 'Lichtgijs'), ('text-primary', 'Yourin Rood'), ('text-deluge', 'Paars'), ('text-piction-blue', 'Blauw'), ('text-mantis', 'Rood-oranje'), ('text-malibu', 'Lichtblauw'), ('text-carrot', 'Oranje'), ('text-red', 'Fel Rood'), ('text-blue-gray', 'Paars-blauw'), ('text-pink', 'Donkerpaars'), ('text-green', 'Groen'), ('text-yellow', 'Geel')], default='text-default', max_length=32, verbose_name='catchphrase kleur'),
        ),
        migrations.AlterField(
            model_name='numbers',
            name='icon_color',
            field=models.CharField(choices=[('text-default', 'Wit'), ('text-black', 'Zwart'), ('text-gray', 'Lichtgijs'), ('text-primary', 'Yourin Rood'), ('text-deluge', 'Paars'), ('text-piction-blue', 'Blauw'), ('text-mantis', 'Rood-oranje'), ('text-malibu', 'Lichtblauw'), ('text-carrot', 'Oranje'), ('text-red', 'Fel Rood'), ('text-blue-gray', 'Paars-blauw'), ('text-pink', 'Donkerpaars'), ('text-green', 'Groen'), ('text-yellow', 'Geel')], default='text-default', max_length=32, verbose_name='kleur icoon'),
        ),
    ]
